name: Delete Preview Environment

inputs:
  localstack-api-key:
    description: 'LocalStack API key used to access the preview environment'
    required: true
  preview_name:
    description: 'The name of the instance to remove'
    required: false
  preview_id:
    description: 'The ID of the pull request. If not provided fallback to PR_ID env variable'
    required: false

runs:
  using: composite
  steps:
    - name: Delete preview environment
      shell: bash
      run: |
        if [[ -n "${{ inputs.preview_name }}" ]]; then
          previewName=preview-${{ inputs.preview_name }}
        elif [[ -n "${{ inputs.preview_id }}" ]]; then
          previewName=preview-${{ inputs.preview_id }}
        elif [[ -n "$PR_ID" ]]; then
          previewName=preview-$PR_ID
        elif [[ -n "${{ github.event.number }}" ]]; then
          previewName=preview-${{ github.event.number }}
        else
          echo "No preview id or preview name provided"
          exit 1
        fi

        response=$(curl -X DELETE \
            -H 'ls-api-key: ${{ inputs.localstack-api-key }}' \
            -H 'authorization: token ${{ inputs.localstack-api-key }}' \
            -H 'content-type: application/json' \
            https://api.localstack.cloud/v1/previews/$previewName)

        if [[ "$response" != "{}" ]]; then
          echo "Unable to delete preview environment. API response: $response"
          exit 1
        fi
