name: Create PR Preview

inputs:
  github-token:
    description: 'Github token used to create PR comments'
    required: true
  localstack-api-key:
    description: 'LocalStack API key used to create the preview environment'
    required: true
  preview-cmd:
    description: 'Command(s) used to create a preview of the PR (can use $AWS_ENDPOINT_URL)'
    required: false
    default: ''
  auto-load-pod:
    description: 'The pod to load on startup of localstack, the env var AUTO_LOAD_POD'
    required: false
    default: ''
outputs:
  LS_PREVIEW_URL: 
    description: 'The URL of LocalStack'
    value: ${{ setps.create-eph-env.outputs.LS_PREVIEW_URL }}
    
runs:
  using: composite
  steps:
    - name: Initial PR comment
      # TODO: potentially replace with Action version number over time
      uses: ./prepare
      if: inputs.github-token
      with:
        github-token: ${{ inputs.github-token }}

    - name: Create preview environment
      id: create-eph-env
      shell: bash
      run: |
        if ! [[ -n "$PR_ID" ]]; then
            echo "Missing pull request id"
            exit 1
        fi
        # TODO: make preview name configurable!
        previewName=preview-$PR_ID

        response=$(curl -X POST -d '{"auto_load_pod": "${{ inputs.auto-load-pod }}"}' \
            -H 'ls-api-key: ${{ inputs.localstack-api-key }}' \
            -H 'authorization: token ${{ inputs.localstack-api-key }}' \
            -H 'content-type: application/json' \
            https://api.localstack.cloud/v1/previews/$previewName)
        endpointUrl=$(echo "$response" | jq -r .endpoint_url)
        if [ "$endpointUrl" = "null" ] || [ "$endpointUrl" = "" ]; then
          echo "Unable to create preview environment. API response: $response"
          exit 1
        fi
        echo "Created preview environment with endpoint URL: $endpointUrl"

        echo "LS_PREVIEW_URL=$endpointUrl" >> $GITHUB_ENV
        echo "AWS_ENDPOINT_URL=$endpointUrl" >> $GITHUB_ENV
        echo "LS_PREVIEW_URL=$endpointUrl" >> $GITHUB_OUTPUT

    - name: Run preview deployment
      shell: bash
      run:
        ${{ inputs.preview-cmd }}
