name: Finish CI Build

inputs:
  github-token:
    description: 'Github token used to create PR comments'
    required: true
  ci-project:
    description: 'Name of the CI project tracked in LocalStack Cloud'
    required: false
  include-preview:
    description: 'Whether to include the created preview URL in the PR comment'
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Update status comment
      uses: actions-cool/maintain-one-comment@v3.1.1
      with:
        token: ${{ inputs.github-token }}
        body: |
          ${{ inputs.ci-project && format('{0}{1}', '🚀 LocalStack Stack Insights and Cloud Pod state for this CI run: https://app.localstack.cloud/ci/', inputs.ci-project) }}
          ${{ inputs.include-preview && format('{0}{1}', '🚀 Preview for this PR: ', env.LS_PREVIEW_URL) }}
          <!-- Sticky Pull Request Comment -->
        body-include: '<!-- Sticky Pull Request Comment -->'
        number: ${{ env.PR_ID }}
