name: LocalStack Test
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '48 23 * * 0'

jobs:
  localstack-action-test:
    name: 'Test LocalStack GitHub Action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start LocalStack
        uses: ./
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
          configuration: DEBUG=1
          use-pro: 'true'
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

      - name: Run Tests against LocalStack
        run: |
          awslocal s3 mb s3://test
          awslocal s3 ls
          echo "Test Execution complete!"

  cloud-pods-test:
    name: 'Test Cloud Pods Action'
    runs-on: ubuntu-latest
    steps:
      - name: ⚡️ Checkout the repository
        uses: actions/checkout@v3

      - name: Start LocalStack
        uses: ./
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
          use-pro: 'true'
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

      - name: Run AWS commands
        run: |
          awslocal s3 mb s3://test
          awslocal sqs create-queue --queue-name test-queue

      - name: Save the Cloud Pod 
        uses: ./
        with:
          state-name: cloud-pods-test
          state-action: save
          no-startup: 'true'
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
