name: LocalStack Ephemeral Instance Test
on:  pull_request

jobs:
  preview-test:
    permissions: write-all
    name: 'Test ephemeral instance workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Ephemeral Instance
        uses: jenseng/dynamic-uses@v1
        with:
          uses: LocalStack/setup-localstack@${{ env.GH_ACTION_VERSION }}
          with: |-
            {
              "github-token": "${{ secrets.GITHUB_TOKEN }}",
              "state-backend": "ephemeral",
              "state-action": "start",
              "skip-ephemeral-stop": "true"
            }
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          GH_ACTION_VERSION: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          
      # We want explicit shutdown
      - name: Shutdown ephemeral instance
        uses: jenseng/dynamic-uses@v1
        with:
          uses: LocalStack/setup-localstack@${{ env.GH_ACTION_VERSION }}
          with: |-
            {
              "github-token": "${{ secrets.GITHUB_TOKEN }}",
              "state-backend": "ephemeral",
              "state-action": "stop"
            }
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          GH_ACTION_VERSION: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
