name: LocalStack Ephemeral Instance Test
on:  pull_request

jobs:
  preview-test:
    permissions: write-all
    name: 'Test ephemeral instance workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Preview
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-backend: preview
          state-action: start
          skip-preview-stop: 'true'
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          
      # We want explicit shutdown
      - name: Shutdown ephemeral instance
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-backend: preview
          state-action: stop
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
